### ISSUE TITLE
TMC Connection Error

### ISSUE THREAD

**Issue by ManiRX100** [bigtreetech/BIGTREETECH-SKR-mini-E3#32] opened 2019-10-06 13:42 UTC
Hi
I followed the same procedure as given for the Marlin Firmware upgrade and got the firmware file. But when I upgrade the board, I get "TMC Connection Error" and the motors are not working properly. I have a BL Touch also installed. And also the board shown in the supplier site and the one I received are a little different near the USB end. Attached is the image.  Need help in this regard. 
![Bigtreetech_Mini_E3](https://user-images.githubusercontent.com/41327045/66270095-2ae15300-e86d-11e9-9e4c-d6087091fef6.JPG)

**Comment by davehardy20** [comment] 2019-10-06 14:59
This is the same for me, I received the board yesterday, and I followed the same procedure as ManiRX100, I have the error 'TMC Connection Error' on the display, however my motors are working!
My BLTouch is not however working properly, when the print starts up the BLTouch self-tests and then once Marlin is booted it does not respond to the commands in the menu ie Reset, deploy etc.

**Comment by ManiRX100** [comment] 2019-10-06 15:05
Hi Dave,
Even I received the board yesterday. The whole day today I was trying to figure this out. Still was not able to solve. My motors are also working.. But in one direction + and not the other way. It doesnt move after 0.00 value.

**Comment by mrBarbecue** [comment] 2019-10-06 15:25
Had the same problem. Removed the red jumper as shown in the picture, so the display showed "Ready". Unfortunately, there is no manual showing us, which jumper configuration means what, but I'm sure, it's about the supply voltage.

**Comment by ManiRX100** [comment] 2019-10-06 16:02
Which jumper should we remove? There is another one at the other end of the board. Actually I removed the one shown in the image I uploaded, but still got the same error.

**Comment by Paddzr** [comment] 2019-10-06 16:15
Tried removing the jumper, still got TMC connection error.

**Comment by davehardy20** [comment] 2019-10-06 17:06
I see a firmware was released 4 hrs ago, marked as 1.2 but cannot try it out as I have no time at the moment

**Comment by Paddzr** [comment] 2019-10-06 17:10
> I see a firmware was released 4 hrs ago, marked as 1.2 but cannot try it out as I have no time at the moment

Tried compiling it, but arduino and platformio both fail.

**Comment by glenmorangie007** [comment] 2019-10-06 17:48
Paddzr - you must install Git client - I've tried this direct from the Zip file and it fails to compile

**Comment by Paddzr** [comment] 2019-10-06 17:52
> Paddzr - you must install Git client - I've tried this direct from the Zip file and it fails to compile

So I installed it but didn't do anything... Tried again and restarted after. Got this error now:

```
.pio\libdeps\STM32F103R_bigtree\Adafruit NeoPixel_ID28\Adafruit_NeoPixel.cpp: In member function 'void Adafruit_NeoPixel::show()':
.pio\libdeps\STM32F103R_bigtree\Adafruit NeoPixel_ID28\Adafruit_NeoPixel.cpp:1736:3: error: 'Pio' was not declared in this scope
   Pio            *port;
   ^~~
.pio\libdeps\STM32F103R_bigtree\Adafruit NeoPixel_ID28\Adafruit_NeoPixel.cpp:1736:19: error: 'port' was not declared in this scope
   Pio            *port;
                   ^~~~
.pio\libdeps\STM32F103R_bigtree\Adafruit NeoPixel_ID28\Adafruit_NeoPixel.cpp:1736:19: note: suggested alternative: 'word'
   Pio            *port;
                   ^~~~
                   word
Compiling .pio\build\STM32F103R_bigtree\libba8\SlowSoftI2CMaster\SlowSoftI2CMaster.cpp.o
.pio\libdeps\STM32F103R_bigtree\Adafruit NeoPixel_ID28\Adafruit_NeoPixel.cpp:1737:12: error: 'WoReg' does not name a type
   volatile WoReg *portSet, *portClear, *timeValue, *timeReset;
            ^~~~~
.pio\libdeps\STM32F103R_bigtree\Adafruit NeoPixel_ID28\Adafruit_NeoPixel.cpp:1740:3: error: 'pmc_set_writeprotect' was not declared in this scope
   pmc_set_writeprotect(false);
   ^~~~~~~~~~~~~~~~~~~~
.pio\libdeps\STM32F103R_bigtree\Adafruit NeoPixel_ID28\Adafruit_NeoPixel.cpp:1741:35: error: 'TC3_IRQn' was not declared in this scope
   pmc_enable_periph_clk((uint32_t)TC3_IRQn);
                                   ^~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio\build\STM32F103R_bigtree\lib578\Adafruit NeoPixel_ID28\Adafruit_NeoPixel.cpp.o] Error 1
=============================================================================================================================================== [FAILED] Took 43.81 seconds =
```

**Comment by glenmorangie007** [comment] 2019-10-06 18:02
Snap PADDZR - I've emailed the results to BigTREE !!

**Comment by glenmorangie007** [comment] 2019-10-06 18:03
PADDZR

at least you now have GIT installed so you can compile

**Comment by Paddzr** [comment] 2019-10-06 18:08
well, mostly. Currently got either board with stepper motors but no BLTouch or board with BLTouch but no stepper motors what so ever. I don't think prints will turn out great without stepper motors being enabled.

I'll wait few days and see how it goes. Maybe someone else comes up with a solution!

**Comment by glenmorangie007** [comment] 2019-10-06 18:09
I'm getting tempted about ripping the damn thing out and going back to my original Ender 3 Board !!

**Comment by davehardy20** [comment] 2019-10-06 18:22
I have put my Creality 1.1.5 board back in for the time being until a solution is found, Bigtreetech need to provide us some decent documentation for this board, if they don't a really awesome upgrade is just gonna go by the wayside. Come on Bigtreetech step up

**Comment by martyboi83** [comment] 2019-10-06 20:06
I am also having the TMC connection error, it is the new board with the different pins.

**Comment by davehardy20** [comment] 2019-10-06 20:26
Regarding the firmware, I took a look at it and it looks like a new upstream version with new board names, platfom.ini default_envs = STM32F103RC_bigtree from Marlin. So I grabbed the latest Marlin 2.0_bugfix and configured it with the above default envs value, and set the other settings as per the setting from the ReadMe.md in this repository. And compiled the firmware in VsCode. Which completed successfully. If someone could try this out on the new SKR E3 Mini board it might help finding a fix. I have pushed the copy of my Marlin 2.0 bugfix build and firmware to my Github here - https://github.com/davehardy20/Marlin_2.0_Bugfix_SKR_E3_Mini_Test, the compiled firmware is in the .pio\build\STM32F103RC_bigtree folder.

**Comment by Paddzr** [comment] 2019-10-06 20:38
> Regarding the firmware, I took a look at it and it looks like a new upstream version with new board names, platfom.ini default_envs = STM32F103RC_bigtree from Marlin. So I grabbed the latest Marlin 2.0_bugfix and configured it with the above default envs value, and set the other settings as per the setting from the ReadMe.md in this repository. And compiled the firmware in VsCode. Which completed successfully. If someone could try this out on the new SKR E3 Mini board it might help finding a fix. I have pushed the copy of my Marlin 2.0 bugfix build and firmware to my Github here - https://github.com/davehardy20/Marlin_2.0_Bugfix_SKR_E3_Mini_Test, the compiled firmware is in the .pio\build\STM32F103RC_bigtree folder once compiled or I put my version in the Releases of my Github repo - https://github.com/davehardy20/Marlin_2.0_Bugfix_SKR_E3_Mini_Test/releases/tag/1.0

Both are 404 right now.

**Comment by davehardy20** [comment] 2019-10-06 20:54
Srry forgot to make it Public, should be fine now

**Comment by Paddzr** [comment] 2019-10-06 21:03
#define Y_DRIVER_TYPE was set to TMS not TMC, 

Tried your bin and then tried compiling the new one from your test source. Both resulted with the TMC Connection Error message.

**Comment by davehardy20** [comment] 2019-10-06 21:11
I have no errors when I build the firmware, only a deprecated library warning at the beginning. Make sure you are online and VSCODE can download any requirements

**Comment by Paddzr** [comment] 2019-10-06 21:15
I think they're warnings more than errors, they're yellow, not red. It compiles it successfully. I've tried few different TMC numbers just to test but all come with the same error.

I've emailed them about it, they just need to release the source code that now comes on the SD card as that one works, but majority of us got to modify it to fit...

**Comment by Paddzr** [comment] 2019-10-06 21:29
https://github.com/Paddzr/SKR-Mini-E3-Stock-FIRMWARE.BIN

Not sure if it's possible to reverse engineer this.

**Comment by ManiRX100** [comment] 2019-10-07 01:14
The new marlin compiled successfully but with the following warnings:
1. .pio\libdeps\STM32F103RC_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x32.c:153:22: warning: 'u8g_dev_ssd1306_128x32_univision_init_seq' defined but not used [-Wunused-const-variable=]
 static const uint8_t u8g_dev_ssd1306_128x32_univision_init_seq[] PROGMEM = { 
2. C:\users\manil\.platformio\packages\framework-arduinoststm32-maple\STM32F1\libraries\STM32ADC\src\utility\util_adc.c:10:30: warning: 'adc_result' initialized and declared 'extern'
 extern volatile unsigned int adc_result = 0;

When I upload this firmware, I am not getting characters in my display. Its just getting on with a blank blue screen.  Hope Bigtreetech comes up with a solution soon for everyone!

**Comment by ManiRX100** [comment] 2019-10-07 01:47
Hi
Can anyone post the image of the new board? I think I have misplaced the two jumpers. I will try to remove the BL Touch and install the Z-Stop switch. Run the stock firmware uploaded by Paddzr and check.

**Comment by davehardy20** [comment] 2019-10-07 10:32
![IMG_20191007_112822](https://user-images.githubusercontent.com/874172/66304848-0b423d00-e8f6-11e9-87d5-80f54836c374.jpg)
This my un-modified board.

**Comment by ManiRX100** [comment] 2019-10-07 11:25
> 
> 
> Regarding the firmware, I took a look at it and it looks like a new upstream version with new board names, platfom.ini default_envs = STM32F103RC_bigtree from Marlin. So I grabbed the latest Marlin 2.0_bugfix and configured it with the above default envs value, and set the other settings as per the setting from the ReadMe.md in this repository. And compiled the firmware in VsCode. Which completed successfully. If someone could try this out on the new SKR E3 Mini board it might help finding a fix. I have pushed the copy of my Marlin 2.0 bugfix build and firmware to my Github here - https://github.com/davehardy20/Marlin_2.0_Bugfix_SKR_E3_Mini_Test, the compiled firmware is in the .pio\build\STM32F103RC_bigtree folder once compiled or I put my version in the Releases of my Github repo - https://github.com/davehardy20/Marlin_2.0_Bugfix_SKR_E3_Mini_Test/releases/tag/1.0

Still the same TMC connection error. What are we supposed to do? Any ideas that Bigtreetech might upload their latest working code in GitHub? Anyone get a reply from them?

**Comment by davehardy20** [comment] 2019-10-07 11:35
The repo has had some updates, since yesterday and BTT have made reference to the the v1.2.zip, which contain firmware. I have tried to compile this and it fails, see the new issue #33.

**Comment by ManiRX100** [comment] 2019-10-07 11:59
> 
> 
> The repo has had some updates, since yesterday and BTT have made reference to the the v1.2.zip, which contain firmware. I have tried to compile this and it fails, see the new issue #33.

Yes.. I too tried with that now and noticed your new thread also. I get an error "command 'platformio-ide.build' not found".

**Comment by Stew-rt** [comment] 2019-10-07 20:04
I don't get this error showing up if I compile against the version newly uploaded to github.
However, I can only confirm that the steppers work as this is all I have tested, as I'm having a seperate issue where I can't get it to power on if my BLTouch is plugged in to either the PROBE or Z-STOP pins. (this was also true of firmware before this version)

**Comment by Paddzr** [comment] 2019-10-07 20:09
> I don't get this error showing up if I compile against the version newly uploaded to github.
> However, I can only confirm that the steppers work as this is all I have tested, as I'm having a seperate issue where I can't get it to power on if my BLTouch is plugged in to either the PROBE or Z-STOP pins. (this was also true of firmware before this version)

Hey, swap your cables around, I had the same issue. The layout doesn't seem to be the same on the 3 pin connector. If your bltouch comes with quick detach cables, just rotate that.

I do however have issues compiling my code....

This is the error: IOError: [Errno 2] No such file or directory: 'c:\\Users\\patry\\Desktop\\Marlin-bugfix-2.0.x\\BIGTREETECH-SKR-mini-E3-master\\firmware\\Marlin-2.0.x-SKR-Mini-E3-v1.2\\.pio\\libdeps\\STM32F103R_bigtree\\_tmp_installing-qeeuxs-package\\SailfishLCD-master\\examples\\FlashForgeInterfaceBoardLCD\\FlashForgeInterfaceBoardLCD.ino':

**Comment by davehardy20** [comment] 2019-10-07 20:18
> I don't get this error showing up if I compile against the version newly uploaded to github.
> However, I can only confirm that the steppers work as this is all I have tested, as I'm having a seperate issue where I can't get it to power on if my BLTouch is plugged in to either the PROBE or Z-STOP pins. (this was also true of firmware before this version)

This is from the FaceBook group page - Hello,here is BIGTREETECH SKR MINI E3 V1.2 notes: We had upgraded some place for SKR MINI E3 V1.2,more detail pls see our file. If your SKR MINI E3 is V1.2 version,pls use our new firmware and we has been uploaded to our github.
About some users are unstable when using BLTOUCH V3.1,Please try :
Use the Z-Stop (PC2) connector. It is more stable than Probe (PC14) connector.
In configuration.h, delete // as below.
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN'

**Comment by Paddzr** [comment] 2019-10-07 20:42
Ok so it compiles, stepper motors are active, now BL touch is giving error. When I try to home it just stops and knocks my octoprint. If I home on the printer it just stays STOPPED. It appears to go up a tiny bit. maybe Z stop issue? I did as dave mentioned and uncommented the #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN'

**Comment by Stew-rt** [comment] 2019-10-07 20:46
Looks like I've been bitten by a change of heart between board versions.
I've just seen the newly uploaded schematic.
Old Board SERVOS socket: |PA1|GND|+5V|
1.2 Board SERVOS socket: |GND|+5V|PA1|
(PROBE and Z-STOP remain the same, |GND|PC14| / |GND|PC2|)
(Just for future reference if anyone has this issue)

**Comment by ManiRX100** [comment] 2019-10-08 02:54
> 
> 
> Looks like I've been bitten by a change of heart between board versions.
> I've just seen the newly uploaded schematic.
> Old Board SERVOS socket: |PA1|GND|+5V|
> 1.2 Board SERVOS socket: |GND|+5V|PA1|
> (PROBE and Z-STOP remain the same, |GND|PC14| / |GND|PC2|)
> (Just for future reference if anyone has this issue)

Are there any modifications needed in the "SKR MINI E3 V1.2" marlin for the BL Touch additionally apart from the changes made by BTT? Can you send the connection image in board for reference please?

**Comment by ManiRX100** [comment] 2019-10-08 06:21
Got it to work currently without BL Touch. The nozzle fan is no noisy compared to before.  I connected it to the fan pin near the X-end stop connector. Is that correct?

**Comment by glenmorangie007** [comment] 2019-10-08 07:17
Connect the nozzle fan to the outer connect and the case cooler to the inner connector

**Comment by glenmorangie007** [comment] 2019-10-08 07:18
Has anyone got a working firmware now which has been tried and tested ??

**Comment by Paddzr** [comment] 2019-10-08 07:25
I’ve got it working. Printed a benchy at .12 layer with .2mm nozzle at 150mm/sec. turned out quite well. With bltouch.

**Comment by davehardy20** [comment] 2019-10-08 07:49
@Paddzr please could you share what you did to get this going? Thanks

**Comment by ManiRX100** [comment] 2019-10-08 08:54
@Paddzr  Yes.. Please share us. BL touch pin connection and the changes in Marlin.. It will be of immense help.

**Comment by glenmorangie007** [comment] 2019-10-08 09:17
Big tree tech have come back and said the firmware will now compile so hopefully I can get the board working properly

**Comment by Paddzr** [comment] 2019-10-08 09:34
Redownload the zip file and it should compile.

**Comment by ManiRX100** [comment] 2019-10-08 13:29
At last made it to work with Bl Touch. The latest firmware from BTT compiles with no issues so far. Thanks everyone for the immense support. Shall I close this thread?

**Comment by ManiRX100** [comment] 2019-10-08 13:30
> 
> 
> Got it to work currently without BL Touch. The nozzle fan is so noisy compared to before. I connected it to the fan pin near the X-end stop connector. Is that correct? Also, can anyone say how to add this board to the Arduino IDE so that I can compile the firmware from Arduino IDE. I checked through the Get board info, it says "Unknown Board".

In between, can anyone suggest how to add this board to Arduino IDE?

**Comment by glenmorangie007** [comment] 2019-10-08 19:00
@ManiRX100 how can you make the BLTouch do the Auto Home from the bed as apposed to going all the way to the x endstop where it is currently doing it ??

**Comment by glenmorangie007** [comment] 2019-10-08 20:02
found it - you have to enable Z_SAFE_HOMING

**Closed** 2019-10-09 12:13 UTC

**Comment by teoyh** [comment] 2019-10-10 14:21
I was having the TMC connection error , i saw the firmware posted by Paddzr 

https://github.com/Paddzr/SKR-Mini-E3-Stock-FIRMWARE.BIN

I downloaded it and flash it to my board and the TMC connection error was gone. 

But my usb connection is not working , how do i compile a new firmware that will not have TMC connection error problem but will get my usb to work in Cura. 

I am using vscode + platformio to compile my firmware , i encounter issue when doing the compilation, is i could not find a right name for the env_default = BIGTREE_SKR_MINI

When i use BIGTREE_SKR_MINI it always throw me error say name is not valid.

**Comment by ManiRX100** [comment] 2019-10-10 14:29
@teoyh . The right name is : env_default = STM32F103R_bigtree.
Download the latest firmware here: https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/firmware/Marlin-2.0.x-SKR-Mini-E3-v1.2.zip

**Comment by teoyh** [comment] 2019-10-10 14:37
> @teoyh . The right name is : env_default = STM32F103R_bigtree.
> Download the latest firmware here: https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/firmware/Marlin-2.0.x-SKR-Mini-E3-v1.2.zip
> This firmware is the latest that worked for the most of us.

Thank you so much i will go and try

**Comment by glenmorangie007** [comment] 2019-10-10 15:15
you don't need to make any changes to the SKR Mini E3 v1.2 unless you are using the BLTouch then use the 

Use the Z-Stop (PC2) connector. It is more stable than Probe (PC14) connector.
In configuration.h, delete // as below.
#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN

check the wiring as the pin configuration for the 3 pin Servo connection is different on this new board

also worth noting that if you are using the BL Touch, you also need to enable the #define Z_SAFE_HOMING or the BL touch will try and autohome at the Endstop on the x axis

**Comment by glenmorangie007** [comment] 2019-10-10 15:36
have you install GIT client - you need this to compile !

**Comment by teoyh** [comment] 2019-10-10 15:41
Oh I see I never install GIT client, I will try again but tomorrow ...very sleepy now, good night

**Comment by martyboi83** [comment] 2019-10-10 20:00
HI, I am still having issues with the TMC connection error? I have compiled the newest v1.2 release in  platformio. I can get it to compile and have burned the firmware to the board using the details in the readme.md (changing the enviroment to STM32F103R_bigtree and MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_2) 

I get a few errors in yellow when it compiles:
pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x32.c:153:22: warning: 'u8g_dev_ssd1306_128x32_univision_init_seq' defined but not used [-Wunused-const-variable=]
 static const uint8_t u8g_dev_ssd1306_128x32_univision_init_seq[] PROGMEM = {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x32.c:83:22: warning: 'u8g_dev_ssd1306_128x32_adafruit2_init_seq' defined but not used [-Wunused-const-variable=]
 static const uint8_t u8g_dev_ssd1306_128x32_adafruit2_init_seq[] PROGMEM = {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x32.c:48:22: warning: 'u8g_dev_ssd1306_128x32_adafruit1_init_seq' defined but not used [-Wunused-const-variable=]
 static const uint8_t u8g_dev_ssd1306_128x32_adafruit1_init_seq[] PROGMEM = {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pio\build\STM32F103R_bigtree\libcda\U8glib-HAL_ID1932\clib\u8g_dev_ssd1306_64x48.c.o
Compiling .pio\build\STM32F103R_bigtree\libcda\U8glib-HAL_ID1932\clib\u8g_dev_ssd1309_128x64.c.o
.pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x64.c:146:22: warning: 'u8g_dev_ssd1306_128x64_univision_init_seq' defined but not used [-Wunused-const-variable=]
 static const uint8_t u8g_dev_ssd1306_128x64_univision_init_seq[] PROGMEM = {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x64.c:44:22: warning: 'u8g_dev_ssd1306_128x64_adafruit1_init_seq' defined but not used [-Wunused-const-variable=]
 static const uint8_t u8g_dev_ssd1306_128x64_adafruit1_init_seq[] PROGMEM = {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

C:\users\martyboi\.platformio\packages\framework-arduinoststm32-maple\STM32F1\libraries\STM32ADC\src\utility\util_adc.c:10:30: warning: 'adc_result' initialized and declared 'extern'
 extern volatile unsigned int adc_result = 0;

I have sent a M122 in pronterface and all I get back is
SENDING:M122
Testing X connection... OK
Testing Y connection... Error: All LOW
Testing Z connection... Error: All LOW
Testing E connection... Error: All LOW

This is driving me mad now, any help would be greatly appreciated

**Comment by glenmorangie007** [comment] 2019-10-10 20:17
@martyboi83 see here :- my compiled FIRMWARE for my Ender 3 - change things in your printer menu before printing - especially the Esteps for your extruder

https://github.com/glenmorangie007/Test

**Comment by martyboi83** [comment] 2019-10-10 20:51
Awesome! thank you, it is working with my v3.1 bltouch

Any idea why i cant get my firmware to work?

**Comment by ManiRX100** [comment] 2019-10-11 01:22
> 
> 
> HI, I am still having issues with the TMC connection error? I have compiled the newest v1.2 release in platformio. I can get it to compile and have burned the firmware to the board using the details in the readme.md (changing the enviroment to STM32F103R_bigtree and MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_2)
> 
> I get a few errors in yellow when it compiles:
> pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x32.c:153:22: warning: 'u8g_dev_ssd1306_128x32_univision_init_seq' defined but not used [-Wunused-const-variable=]
> static const uint8_t u8g_dev_ssd1306_128x32_univision_init_seq[] PROGMEM = {
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> .pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x32.c:83:22: warning: 'u8g_dev_ssd1306_128x32_adafruit2_init_seq' defined but not used [-Wunused-const-variable=]
> static const uint8_t u8g_dev_ssd1306_128x32_adafruit2_init_seq[] PROGMEM = {
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> .pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x32.c:48:22: warning: 'u8g_dev_ssd1306_128x32_adafruit1_init_seq' defined but not used [-Wunused-const-variable=]
> static const uint8_t u8g_dev_ssd1306_128x32_adafruit1_init_seq[] PROGMEM = {
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Compiling .pio\build\STM32F103R_bigtree\libcda\U8glib-HAL_ID1932\clib\u8g_dev_ssd1306_64x48.c.o
> Compiling .pio\build\STM32F103R_bigtree\libcda\U8glib-HAL_ID1932\clib\u8g_dev_ssd1309_128x64.c.o
> .pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x64.c:146:22: warning: 'u8g_dev_ssd1306_128x64_univision_init_seq' defined but not used [-Wunused-const-variable=]
> static const uint8_t u8g_dev_ssd1306_128x64_univision_init_seq[] PROGMEM = {
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> .pio\libdeps\STM32F103R_bigtree\U8glib-HAL_ID1932\src\clib\u8g_dev_ssd1306_128x64.c:44:22: warning: 'u8g_dev_ssd1306_128x64_adafruit1_init_seq' defined but not used [-Wunused-const-variable=]
> static const uint8_t u8g_dev_ssd1306_128x64_adafruit1_init_seq[] PROGMEM = {
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> C:\users\martyboi.platformio\packages\framework-arduinoststm32-maple\STM32F1\libraries\STM32ADC\src\utility\util_adc.c:10:30: warning: 'adc_result' initialized and declared 'extern'
> extern volatile unsigned int adc_result = 0;
> 
> I have sent a M122 in pronterface and all I get back is
> SENDING:M122
> Testing X connection... OK
> Testing Y connection... Error: All LOW
> Testing Z connection... Error: All LOW
> Testing E connection... Error: All LOW
> 
> This is driving me mad now, any help would be greatly appreciated
Yellow colored are warnings, not errors. I got the same warnings, but the firmware works.

**Comment by ManiRX100** [comment] 2019-10-11 01:24
@martyboi83 Yellow colored are warnings, not errors. I got the same errors, but the firmware works fine.

**Comment by Arganaz** [comment] 2019-10-11 11:22
Just comment  EEPROM_SETTINGS as defined in [https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V1.2](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V1.2)
TMC ERROR will be gone.

**Comment by glenmorangie007** [comment] 2019-10-11 11:29
@Arganaz EEPROM_SETTINGS are defined in mine as the release originally has it in and I don't get any TMC Errors

**Comment by wstrzalka** [comment] 2019-11-02 11:22
I had the same. Ensure you're powering the board with main power not via USB. Otherwise you'll get "TMC Connection error" regardless what version you try.

**Comment by Dude2475** [comment] 2019-11-07 11:57
> I had the same. Ensure you're powering the board with main power not via USB. Otherwise you'll get "TMC Connection error" regardless what version you try.

How can i do this ?

**Comment by The-Monkey-King** [comment] 2019-11-09 02:00
> 
> 
> > I had the same. Ensure you're powering the board with main power not via USB. Otherwise you'll get "TMC Connection error" regardless what version you try.
> 
> How can i do this ?

Ignore Teaching Tech's video for now. The best thing to do is compile Big Tree Tech's Marlin branch (see @Arganaz above), load it on to the SD Card, and then rewire the new board, Just to test, all you need to do is wire the black and red power leads to the board (the largest screw block on the board, point to the left too). Also plus in the old screen cable in the only place it will fit on the right side of the board. Plug in the power and turn it on. The message should be a normal "SKR... ready" and not the TMC Connection error.

**Comment by gotdsm95** [comment] 2019-11-25 06:25
I am still getting the tmc connection error. I can move all axis besides X. if i switch steppers and or cables the problem follows the X axis. I used the lastest firmware to date from BTT repo.

**Comment by Aleix-casa** [comment] 2020-01-07 22:46
does anyone kow how to fix this error for a DIP v1.0?

**Comment by chazzin** [comment] 2020-01-08 01:06
I have added an SN04 to support auto-leveling on my Ender-3, driving it with just 5V. Have ordered 24V opto-isolator and plane to drive the sensor at 24v to see if I can capitalize on the higher accuracy and put the glass back on my bed. Since I am not very circuit savvy yet I am hoping for some input for the 24V alteration using the OPTO-isolator. Currently pulling +5 of SPI and connecting signal/gnd to Z-stop pins. Not yet certain of exactly this wiring should work with opto-isolator in place. 
This is the opto-isolator I ordered:

**5V/12V/24V 1 Channel 220V One-Way Optical Isolation Relay Driver Board Module SV-5A1R1P-N Optocoupler Controller for PLC Control Module Component**

[https://www.amazon.com/Isolation-SV-5A1R1P-N-Optocoupler-Controller-Component/dp/B07QSWN3WP/ref=sr_1_1?keywords=5V%2F12V%2F24V+1+Channel+220V+One-Way+Optical+Isolation+Relay+Driver+Board+Module+SV-5A1R1P-N+Optocoupler+Controller+for+PLC+Control+Module+Component&qid=1578445428&s=industrial&sr=1-1-catcorr](url)

Any  input or suggestions would be appreciated.  (I do not want to Fry my motherboard yet. )

**Comment by ManiRX100** [comment] 2020-01-08 01:28
> does anyone kow how to fix this error for a DIP v1.0?

Is it the TMC connection error?

**Comment by gotdsm95** [comment] 2020-01-08 01:42
My tmc error ended up just being a bad board. Got a new one and has worked perfectly since.

**Comment by zikwin** [comment] 2020-01-08 05:53
> > does anyone kow how to fix this error for a DIP v1.0?
> 
> Is it the TMC connection error?

do you know how to solve it TMC connecttion error on DIP v1.0 ?

**Comment by zikwin** [comment] 2020-01-08 08:39
> My tmc error ended up just being a bad board. Got a new one and has worked perfectly since.

how you determine that is the bad board... got any method to test it?

**Comment by Aleix-casa** [comment] 2020-01-08 09:57
I just found a solution and for my case was really easy , just download the firmware with the name of the drivers you have, 
https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/tree/master/Firmware

change the name of the file to "firmware" (sounds really stupid but I was wasting a few hours trying to understand why is my printer not updating) in my case was the "firmware-tmc2208-chip-on-bottom.bin" and that's it.

Also, when I was looking for a solution I found some guy who solder a couple of pins for the TMC2208 UART, I don't really know if that was necessary or the problem was just the firmware but I did it and the printer work

**Comment by perkins2166** [comment] 2020-03-16 18:49
has anyone thought to hit the reset button on the BTT mini3 board?

**Comment by JWolfJr** [comment] 2020-03-16 20:09
I had powered off then on the board a few times trying to reset the problem, not being smart here, but I thought that would do the same as the reset button!?

**Comment by perkins2166** [comment] 2020-03-16 21:12
No worries no offense taken. I've been catching up on this string and no one has mentioned the obvious hit the reset, now that base is covered.

**Comment by JWolfJr** [comment] 2020-03-16 23:10
I might be wrong. I have not looked into any trace pcb drawing to see if the reset button interrupts the power circuit somehow.  I just assumed, you know what they say about that.  The frugal side of me wishes there were a fix, seems like a waste to throw out the whole board for something so small.  I have direct cooling on the heat sinks of the drivers with no wires near them, so far so good! Keeping my fingers crossed, I really do like this board.

**Comment by perkins2166** [comment] 2020-03-17 00:52
Yeah me to, I bought the latest SKR mini3 E3 and the TFT35 display. While I was working with the TFT touch the SKR mother board went south, TMC connection error! Yeah everything was off. I think the TFT touch screen is the cause. There aren’t any obvious reasons for the TMC error that make sense. Send the boards back if they fail, if BBT gets enough of them they will get the message. Money gets everyone’s attention sooner or later.
I sent it back to amazon for a replacement. I put in the new board loaded V2.0.5 with the original screen. The printed works fine? 
  After 40 years of working on electromechanical business equipment consider cheap boards as black boxes, pull it out replace turn on. If it doesn’t work repeat.

Regards
Dan Perkins
Perkins2166@twc.com

**Comment by VietTPham** [comment] 2020-04-20 02:08
I got the same error, and I just flashed the stock firmware they had that matched your TMC driver and got rid of the error.

**Comment by The-Monkey-King** [comment] 2020-06-12 04:31
I had a thermal runaway event when using PETG on my Ender-3 with a V6 installed. After rebooting I got this same error message. Most likely I will need to trace a short somewhere on the board. My SKR v1.3 had an issue with the posts for the 12v power supply were not soldered correctly and thereby shorted the board. Most likely for this specific error, you have a trace overlapping the USB connection. For others, the board is most likely damaged and needs to be sent back or a new one provided. The lifetime on these BTT boards seems to be dwindling fast, even before COVID.

**Comment by perkins2166** [comment] 2020-06-12 11:37
Thank you. 

Regards
Dan Perkins
Perkins2166@twc.com

**Comment by hazedav** [comment] 2020-12-29 08:41
> I had a thermal runaway event when using PETG on my Ender-3 with a V6 installed. After rebooting I got this same error message. Most likely I will need to trace a short somewhere on the board. My SKR v1.3 had an issue with the posts for the 12v power supply were not soldered correctly and thereby shorted the board. Most likely for this specific error, you have a trace overlapping the USB connection. For others, the board is most likely damaged and needs to be sent back or a new one provided. The lifetime on these BTT boards seems to be dwindling fast, even before COVID.

This same exact thing pretty much happened to me.  Did you come to a resolution besides replacing the board?

**Comment by titansmu2** [comment] 2022-06-25 01:05
hi,
   i have simple solution for this tmc driver through low error. In marlin firmware change  the driver tmc2209 into A4988. This is the one solution.
second thing ,if you get this error disconnect again connect make sure that your board was externally powered.
